### ISSUE TITLE
doesnt execute

### ISSUE THREAD

**Issue by yofriendfromschool1** [Mistercoolertyper/Krampus-SynUI#1]
i press attach then after its done it doesnt execute

**Comment by Mistercoolertyper** [comment]
Executing should work fine as long as loader.live isn't down and you provided the right login token. loader.live is down rn so it won't work anyways but when it's back up you can try to delete the file named "launch.cfg" in the folder of the UI, then reopen and make sure you put the correct login token in, also make sure that krampus is the only exe in the folder you selected when you first pressed attach.

**Comment by Mistercoolertyper** [comment]
this should be fully fixed now since i switched to another method for actually executing cuz the loader.live websocket is gone
